FROM tiangolo/uvicorn-gunicorn:python3.11-slim

# RUN apt-get update && apt-get install -y netcat
# RUN apt-get update && apt-get install -y netcat-traditional
# RUN apt-get update && apt-get install -y netcat-openbsd

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
