services:

  traefik:
    image: traefik:v2.10.4
    container_name: traefik
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - 80:80
      - 8080:8080
    restart: always
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: 
      # Enable Docker in Traefik, so that it reads labels from Doker services
      - --providers.docker
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Create a entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Dashboard
      - --api.insecure # Don't do that in production# 
    networks:
      - traefik-public

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services taht need to be publicly available via this Traefik
  traefik-public:
    external: true