version: '3.8'

services:
  backend:
    build: ./
    container_name: backend
    restart: always
    labels:
      # Enable Traefik for this specific "backend" service
      - traefik.enable=true
      # Our service listens on 8082 labels:
      - --port=80
      # Define the port inside of the Docker service to use
      - traefik.http.services.app.loadbalancer.server.port=80
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`localhost`)
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public    

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services taht need to be publicly available via this Traefik
  traefik-public:
    external: true